### ISSUE TITLE
实际上 服务管理的平台没有开源出来？？？

### ISSUE THREAD

**Issue by WuHanMuMu** [tars-node/Tars.js#1]
-- 最重要的不开源，使用价值意义不大了###

**Comment by hellovigoss** [comment]
lol

**Comment by womo2014** [comment]
Tars 平台开源在这里 https://github.com/Tencent/Tars

**Comment by medns** [comment]
Tars 管理平台相关的开源项目在这里 https://github.com/Tencent/Tars
您可以直接搭建一整套完整的系统

**Comment by WuHanMuMu** [comment]
好的，谢谢，这个管理平台不是node写的是吧--

**Comment by medns** [comment]
后台的部分是用C++实现的
